name: Hourly Price Check
on:
  schedule:
    - cron: '*/5 * * * *' # This means "at the start of every hour"
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
     # ... (keep the top part the same until 'Run analysis')
      - name: Run analysis
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: python tracker.py

      - name: Commit and Push the note
        run: |
          git config --global user.name "CryptoBot"
          git config --global user.name "bot@github.com"
          git add log.txt
          git commit -m "Update price log" || exit 0
          git push
